# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:cauldron rig_hash set value '39524a47790baf8a64aa6e7237d84cc8c194c25c71fda98598f332226268249b'
scoreboard objectives add aj.in.frame dummy
scoreboard objectives add aj.out.frame dummy
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.fail.frame dummy