# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$kill $(head)
$kill $(tail)
$kill $(leg1)
$kill $(leg2)
$kill $(leg3)
$kill $(leg4)
$kill $(body)