# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s CustomName set value ['',{text:aj.fire_fox,color:'#00aced'},'.',{text:bone,color:light_purple},'.',{text:leg3,color:gold}]
function animated_java:global/gu/get_entity_uuid_string
scoreboard players operation @s aj.id = aj.last_id aj.id