# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function aj:cauldron/animations/idle/zzz/frames/last_frame_effects with storage animated_java:temp entry.data.uuids_by_name
scoreboard players add @s aj.idle.frame 1