# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.cauldron.animation.in.playing
tag @s remove aj.cauldron.animation.out.playing
tag @s remove aj.cauldron.animation.idle.playing
tag @s remove aj.cauldron.animation.fail.playing