# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(stick) { transformation: [-0.7071f,0f,-0.7071f,0.3125f,0f,1f,0f,0.9375f,0.7071f,0f,-0.7071f,-0.1875f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(side) { transformation: [-1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(left_handles) { transformation: [-1f,0f,0f,0.375f,0f,1f,0f,0.5f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(right_handles) { transformation: [-1f,0f,0f,-0.375f,0f,1f,0f,0.5f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(root) { transformation: [-1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: -1 }