# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(stick) {transformation: [-0.7071f,0f,-0.7071f,0.3125f,0f,0.9333f,0f,0.925f,0.7071f,0f,-0.7071f,-0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(side) {transformation: [-1f,0f,0f,0f,0f,0.9333f,0f,0.05f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_handles) {transformation: [-0.7193f,-0.6947f,0f,0.375f,-0.6483f,0.6714f,0f,0.5167f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_handles) {transformation: [-0.7193f,0.6947f,0f,-0.375f,0.6483f,0.6714f,0f,0.5167f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-1f,0f,0f,0f,0f,0.9333f,0f,0.05f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}