# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(stick) {transformation: [-0.7071f,0f,-0.7071f,0.3125f,0f,1.05f,0f,1.1094f,0.7071f,0f,-0.7071f,-0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(side) {transformation: [-1f,0f,0f,0f,0f,1.05f,0f,0.125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_handles) {transformation: [-0.8021f,-0.5972f,0f,0.375f,-0.627f,0.8422f,0f,0.65f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_handles) {transformation: [-0.8021f,0.5972f,0f,-0.375f,0.627f,0.8422f,0f,0.65f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-1f,0f,0f,0f,0f,1.05f,0f,0.125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}