# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=aj.fire_fox.animation.walk.playing] run function aj:fire_fox/animations/walk/zzz/on_tick
execute on passengers run rotate @s ~ ~