# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function aj:fire_fox/animations/walk/zzz/frames/last_frame_effects with storage animated_java:temp entry.data.uuids_by_name
scoreboard players add @s aj.walk.frame 1