# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=aj.cauldron.animation.in.playing] run function aj:cauldron/animations/in/zzz/on_tick
execute if entity @s[tag=aj.cauldron.animation.out.playing] run function aj:cauldron/animations/out/zzz/on_tick
execute if entity @s[tag=aj.cauldron.animation.idle.playing] run function aj:cauldron/animations/idle/zzz/on_tick
execute if entity @s[tag=aj.cauldron.animation.fail.playing] run function aj:cauldron/animations/fail/zzz/on_tick
execute on passengers run rotate @s ~ ~