# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:fire_fox rig_hash set value '4ee73438edecbce1b1bafa3a4c937434a65d06bb2d9d86d9019fa13f8601ee54'
scoreboard objectives add aj.walk.frame dummy