# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
# Data Manager: Initalize per-entity storage
function animated_java:global/gu/get_entity_uuid_string
data modify storage animated_java:temp args.uuid set from storage animated_java:gu out
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
function animated_java:global/data_manager/create_entry with storage animated_java:temp args
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.root_uuid set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.blueprint_id set value "aj:fire_fox"
data modify storage animated_java:temp entry.data.rig_hash set value "4ee73438edecbce1b1bafa3a4c937434a65d06bb2d9d86d9019fa13f8601ee54"
tp @s ~ ~ ~ ~ ~
execute on passengers if entity @s[tag=aj.fire_fox.node.head] run function aj:fire_fox/zzz/summon/as_node/head
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.head set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.fire_fox.node.tail] run function aj:fire_fox/zzz/summon/as_node/tail
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.tail set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.fire_fox.node.leg1] run function aj:fire_fox/zzz/summon/as_node/leg1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.leg1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.fire_fox.node.leg2] run function aj:fire_fox/zzz/summon/as_node/leg2
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.leg2 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.fire_fox.node.leg3] run function aj:fire_fox/zzz/summon/as_node/leg3
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.leg3 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.fire_fox.node.leg4] run function aj:fire_fox/zzz/summon/as_node/leg4
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.leg4 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.fire_fox.node.body] run function aj:fire_fox/zzz/summon/as_node/body
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.body set from storage animated_java:gu out
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function aj:fire_fox/zzz/set_default_pose
execute if data storage animated_java:temp args.variant run function aj:fire_fox/zzz/summon/zzz/variant_arg/no_variants_warning
execute if score #success aj.i matches 0 run return fail
execute if data storage animated_java:temp args.animation run function aj:fire_fox/zzz/summon/animation_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
execute on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 1
execute on passengers run data modify entity @s teleport_duration set value 1
tag @s remove aj.new
execute on passengers run tag @s remove aj.new