# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head) { transformation: [-1f,0f,0f,-0.0625f,0f,1f,0f,-0.375f,0f,0f,-1f,0.375f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(tail) { transformation: [-1f,0f,0f,0f,0f,0f,1f,-0.2813f,0f,1f,0f,-0.375f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(leg1) { transformation: [-1f,0f,0f,-0.125f,0f,1f,0f,-0.4688f,0f,0f,-1f,-0.2188f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(leg2) { transformation: [-1f,0f,0f,0.125f,0f,1f,0f,-0.4688f,0f,0f,-1f,-0.2188f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(leg3) { transformation: [-1f,0f,0f,-0.125f,0f,1f,0f,-0.4688f,0f,0f,-1f,0.2187f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(leg4) { transformation: [-1f,0f,0f,0.125f,0f,1f,0f,-0.4688f,0f,0f,-1f,0.2187f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(body) { transformation: [-1f,0f,0f,0f,0f,0f,1f,-0.3437f,0f,1f,0f,0.3125f,0f,0f,0f,1f], start_interpolation: -1 }