# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
# Data Manager: Initalize per-entity storage
function animated_java:global/gu/get_entity_uuid_string
data modify storage animated_java:temp args.uuid set from storage animated_java:gu out
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
function animated_java:global/data_manager/create_entry with storage animated_java:temp args
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.root_uuid set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.blueprint_id set value "aj:cauldron"
data modify storage animated_java:temp entry.data.rig_hash set value "39524a47790baf8a64aa6e7237d84cc8c194c25c71fda98598f332226268249b"
tp @s ~ ~ ~ ~ ~
execute on passengers if entity @s[tag=aj.cauldron.node.stick] run function aj:cauldron/zzz/summon/as_node/stick
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.stick set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.cauldron.node.side] run function aj:cauldron/zzz/summon/as_node/side
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.side set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.cauldron.node.left_handles] run function aj:cauldron/zzz/summon/as_node/left_handles
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.left_handles set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.cauldron.node.right_handles] run function aj:cauldron/zzz/summon/as_node/right_handles
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.right_handles set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.cauldron.node.root] run function aj:cauldron/zzz/summon/as_node/root
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.root set from storage animated_java:gu out
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function aj:cauldron/zzz/set_default_pose
execute if data storage animated_java:temp args.variant run function aj:cauldron/zzz/summon/zzz/variant_arg/no_variants_warning
execute if score #success aj.i matches 0 run return fail
execute if data storage animated_java:temp args.animation run function aj:cauldron/zzz/summon/animation_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
execute on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 1
execute on passengers run data modify entity @s teleport_duration set value 1
tag @s remove aj.new
execute on passengers run tag @s remove aj.new